[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 100
dimensions.lines = 40
padding.x = 30
padding.y = 30

decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

size = 14
