[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.92
blur = true

[font]
normal.family = "JetBrains Mono"
normal.style = "Regular"
size = 14
